apiVersion: apps/v1
kind: Deployment
metadata:
  name: msg-mock
  labels:
    app: msg-mock
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msg-mock
  template:
    metadata:
      labels:
        app: msg-mock
    spec:
      containers:
        - name: msg-mock
          image: jeremiahchienda/msg-mock:latest
          ports:
            - containerPort: 3001
          env:
            - name: SGW_BASE_URL
              value: "http://sync-gateway-no-wine.msgateway.svc.cluster.local:4985"
            - name: SERVER_PORT
              value: "3001"
            - name: COUCHBASE_URL
              value: "no-wine.msgateway.svc.cluster.local"
            - name: COUCHBASE_READS_DB
              value: "offline-reads"
            - name: COUCHBASE_WRITES_DB
              value: "offline-writes"
            - name: COUCHBASE_USER
              valueFrom:
                secretKeyRef:
                  name: my-user-secret
                  key: username
            - name: COUCHBASE_PASS
              valueFrom:
                secretKeyRef:
                  name: my-password-secret
                  key: password
---
#service
apiVersion: v1
kind: Service
metadata:
  name: msg-mock
spec:
  type: NodePort
  selector:
    app: msg-mock
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3001
      nodePort: 31655
